services:
  - type: web
    name: ner-sahayak-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production

  - type: web
    name: ner-sahayak-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ner-sahayak-backend
          property: host
