// Central Roster of 10 Registered Drivers for North East India Logistics

export const DRIVER_ROSTER = [
  {
    id: 'drv-1',
    name: 'Arjun Bora',
    email: 'arjun@ner-sahayak.in',
    phone: '+91 98765 43210',
    vehicleNumber: 'AS 01 K 4309',
    district: 'Kamrup Metropolitan',
    state: 'Assam',
    status: 'active',
    cargoType: 'Medical Supplies',
    experienceYears: 8,
  },
  {
    id: 'drv-2',
    name: 'Bikram Das',
    email: 'bikram@ner-sahayak.in',
    phone: '+91 98765 43211',
    vehicleNumber: 'AS 02 C 8812',
    district: 'Nagaon',
    state: 'Assam',
    status: 'available',
    cargoType: 'Essential Grains & Ration',
    experienceYears: 10,
  },
  {
    id: 'drv-3',
    name: 'Chandan Kalita',
    email: 'chandan@ner-sahayak.in',
    phone: '+91 98765 43212',
    vehicleNumber: 'AS 06 F 1045',
    district: 'Dibrugarh',
    state: 'Assam',
    status: 'available',
    cargoType: 'Oil & Petroleum Distillates',
    experienceYears: 12,
  },
  {
    id: 'drv-4',
    name: 'Dipankar Saikia',
    email: 'dipankar@ner-sahayak.in',
    phone: '+91 98765 43213',
    vehicleNumber: 'TR 01 A 5521',
    district: 'Agartala',
    state: 'Tripura',
    status: 'available',
    cargoType: 'Agricultural Freight',
    experienceYears: 6,
  },
  {
    id: 'drv-5',
    name: 'Eshaan Chettri',
    email: 'eshaan@ner-sahayak.in',
    phone: '+91 98765 43214',
    vehicleNumber: 'SK 04 P 9934',
    district: 'Gangtok',
    state: 'Sikkim',
    status: 'available',
    cargoType: 'Cold Storage Vaccines',
    experienceYears: 9,
  },
  {
    id: 'drv-6',
    name: 'Farhan Ahmed',
    email: 'farhan@ner-sahayak.in',
    phone: '+91 98765 43215',
    vehicleNumber: 'ML 05 D 7710',
    district: 'Shillong',
    state: 'Meghalaya',
    status: 'available',
    cargoType: 'Heavy Infrastructure Materials',
    experienceYears: 11,
  },
  {
    id: 'drv-7',
    name: 'Gautam Gogoi',
    email: 'gautam@ner-sahayak.in',
    phone: '+91 98765 43216',
    vehicleNumber: 'AS 03 E 4482',
    district: 'Jorhat',
    state: 'Assam',
    status: 'available',
    cargoType: 'Tea Export Cargo',
    experienceYears: 7,
  },
  {
    id: 'drv-8',
    name: 'Haokip Zou',
    email: 'haokip@ner-sahayak.in',
    phone: '+91 98765 43217',
    vehicleNumber: 'MN 01 L 3319',
    district: 'Imphal',
    state: 'Manipur',
    status: 'available',
    cargoType: 'Emergency Disaster Relief Supplies',
    experienceYears: 14,
  },
  {
    id: 'drv-9',
    name: 'Inaobi Singh',
    email: 'inaobi@ner-sahayak.in',
    phone: '+91 98765 43218',
    vehicleNumber: 'NL 07 B 2291',
    district: 'Dimapur',
    state: 'Nagaland',
    status: 'available',
    cargoType: 'Hardware & Machinery Parts',
    experienceYears: 5,
  },
  {
    id: 'drv-10',
    name: 'Jiten Teron',
    email: 'jiten@ner-sahayak.in',
    phone: '+91 98765 43219',
    vehicleNumber: 'AR 02 H 6604',
    district: 'Itanagar',
    state: 'Arunachal Pradesh',
    status: 'available',
    cargoType: 'Border Security & Ration Freight',
    experienceYears: 15,
  },
];
